### ISSUE TITLE
Ships example missing file train.tscn or one of its dependencies

### ISSUE THREAD

**Issue by rudzikdawid** [edbeeching/godot_rl_agents_examples#12]
OS: Fedora 36
git: 2.41.0

it seems Ship projects in this repo is broken
i downloaded repo as zip from github, unpack, import Ship project in Godot 4.1 and get error `Ships example missing file train.tscn or one of its dependencies`

So i downloaded repo again but this time using git 2.41.0 but with the same results
binary files in assets directory seems broken

from Ship project only health_bar.tsnc and chest.tsnc opens correctly

is the problem due to LFS?

I also tried with FlyBy example and everything works fine

**Comment by Ivan-267** [comment]
Hello and thank you for reporting this. I can also confirm this with the latest commit of the repository, I don't have the option to download the LFS files, only to initialize LFS in Sourcetree (a GUI for Git). Some files are just LFS pointers, this is what likely caused the errors you've mentioned.

What worked for me is to locally move to this commit: https://github.com/edbeeching/godot_rl_agents_examples/commit/33fdaee40866ef4dba5c788da5fa33a19a1a83c1 and then pull the LFS content. You might be able to do the same as a temporary solution. You might be able to move back to the latest commit after so that all of the other examples will work as well.

My guess is that the content is still stored with LFS for this example, but the newest version of the repo is not set to use LFS (this was done due to some issues with LFS files not working properly with the other examples).

**Comment by edbeeching** [comment]
Ok looks like fixing one problem created another, I will take a look tonight.

**Comment by metinc** [comment]
I can confirm it's working now so this issue can be closed.
