### ISSUE TITLE
3d Car Parking scenes invalid/corrupt

### ISSUE THREAD

**Issue by BmanClark** [edbeeching/godot_rl_agents_examples#17]
On Windows, Godot 4.1.2, both training and testing scene come up "invalid or corrupt" and don't load for the 3D Car Parking example.

**Comment by Ivan-267** [comment]
Hello, thank you for reporting this. 

I'm on Windows 10, 64 bit, and I just tried the following steps and the environment worked for me:
- I downloaded the examples repository as zip from here: https://github.com/edbeeching/godot_rl_agents_examples using `Code > Download Zip`
- In Godot, I imported the examples\3DCarParking project

The Godot versions I tried include 4.2 stable 64 bit mono / .net, and 4.1.2 stable 64 bit mono / .net from here: https://godotengine.org/download/archive/4.1.2-stable/

Can you describe the steps that produced the issue and was the Godot version the same as above? Would you be able to also try Godot 4.2 stable 64 bit .NET and see if you get the same error?

**Comment by metinc** [comment]
Make sure you have Blender installed.

**Comment by Ivan-267** [comment]
Some of the examples are made or exported with Godot 4.2 so it might be useful to have it if possible, and while not all of the examples use Blender / Blend files, most of the newer ones do so it would be useful to have Blender installed as well.

You may need to configure the Blender path in `Editor` > `Editor Settings`:
![image](https://github.com/edbeeching/godot_rl_agents_examples/assets/61947090/f06b8dbb-e82e-428a-9caf-d4fe29b30756)

Regarding having a message that mentions that Blender is missing, I agree it would be useful.

I have also added a little note about requirements (https://github.com/edbeeching/godot_rl_agents_examples/blob/3d_lander_example/README.md) since more people are likely to run into the same issue.

**Comment by rafavital** [comment]
Hey there! 

I've been facing the same issue, only difference is that I'm running MacOS, Godot doesn't seem to recognize blender.app as an installation. Currently no luck trying to get around this. Wouldn't it be better to have the 3D models as GTLFs, as it's Godot's standard model format?

Thanks in advance.

**Comment by rafavital** [comment]
On MacOS I was able to fix it for the Ships example which was having the same problem. I just set Blender3 Import Path as "/Applications/Blender.app/Contents/MacOS", either by setting it in the popup dialog that appears the first time I import the project or when the project's already open by going into Project Settings>FileSystem>Import. 

I was able to find this path by right-clicking the Blender.app file in the /Applications folder and clicking on "Show Package Content"

**Comment by DQN-Labs** [comment]
I had the same problem. I'm also on macOS, and setting the path to my Blender executable seemed to fix all the issues.

**Comment by edbeeching** [comment]
Closing, let me know if you have any further issues.
